### ISSUE TITLE
Train Iternorm

### ISSUE THREAD

**Issue by Blackpinkup** [shachoi/RobustNet#13]
Thanks for your great work again. I have tested all trained model. Now I want to train iw, ibn, iternorm,sw on those datasets. You have provided many scripts, that's amazing, but I can't find the training script for Iternorm. Since you have trained model of Iternorm, I think you can tell me how to train Iternorm. 
I would appreciate it if you could help me solve this problem, thanks again.

**Comment by shachoi** [comment]
Sorry for the very late reply.
Itternorm code is difficult to provide. sorry.

**Comment by Blackpinkup** [comment]
Thanks for your reply，we cite your work in our article and paste some experimental results on RobustNet without iternorm. Anyway，RobustNet is a great project.
