### ISSUE TITLE
which version of Mapillary Vistas Dataset is used ? 

### ISSUE THREAD

**Issue by txsing** [shachoi/RobustNet#14]
A lot of thanks for the work!

Currently, in the official Mapillary Vistas Dataset websites, there are two versions 

- mapillary-vistas-dataset_public_v1.2.zip
- mapillary-vistas-dataset_public_v2.0.zip

Which one should I download?  BTW is there any way to download this dataset by command line instead of web-click?

**Comment by shachoi** [comment]
Sorry for the very late response.
The Mapillary dataset seems to have been upgraded to v2.0 in 2021. We used v1.2.
It seems that it is not easy with a command such as "wget" because a login is required to download.

Thanks!
