### ISSUE TITLE
Can not obtain the reported baseline performance

### ISSUE THREAD

**Issue by fanq15** [shachoi/RobustNet#15]
Thank you very much for this great work!
I am trying to train the baseline model based on your code.
However, I can not obtain the reported baseline performance.

I use Cityscapes train set to train the model and test the model on BDD-100K.
But the baseline performance is only 42.7, which is 2.3 mIoU lower than your baseline (44.96).

**Comment by fanq15** [comment]
It seems because that I used 8 GPUs to train the model and set the total training iteration from 40000 to 10000.

**Comment by shachoi** [comment]
Yes, iteration has a significant impact on performance.
Additionally, it may be difficult to reproduce the exact number because the development environment, such as GPU, CUDA version, random seed etc., must exactly match.
