### ISSUE TITLE
Question about the channel of featuremap

### ISSUE THREAD

**Issue by zhShen-oc** [shachoi/RobustNet#18]
hi, author, thank you for your great work.
i read the version of code "train_r50os16_cty_isw.sh", the config parameter **wt_layer** is [0 0 2 2 2 0 0]. 
when i dive into code , i found '0' in wt_layer means w_arr will not append featuremap, and '2' means w_arr will append one featuremap. Therefore there are total 3 featuremap in w_arr, while the picture in paper said C = 7.   
![image](https://user-images.githubusercontent.com/41111448/167605921-c5a1dae0-0c42-4f2a-af86-e4e6ba452551.png)
I have not run the code, could you tell me the right channel of featuremap?

**Comment by shachoi** [comment]
Hi,
wt_layer indicates the layer to which the ISW is applied. This is not related to the figure. C=7 in the figure denotes the channel dimension of a feature map (this is just an example for explanation).
wt_layer [0 0 2 2 2 0 0] means that ISW is applied to the 3rd, 4th, and 5th layer of the model.

Best regards.
Sungha.
