### ISSUE TITLE
about the directory structures

### ISSUE THREAD

**Issue by SvenSu** [shachoi/RobustNet#2]
Thank you for your outstanding work. You only give the file structure of Cityscapes, but you don't provide the file structure of gtav, Synthia, BDD, etc. can you provide them?

**Comment by shachoi** [comment]
Sorry for the delayed reponse.
I have updated "README.md" file including the folder tree of other datasets.

Thank you for your interest in our work!

**Comment by feipan664** [comment]
Dear author, thank you so much for sharing this code. For SYNTHIA dataset, I couldn't not find information about train split/val split. How do you split SYNTHIA dataset in the experiment? 
Best regards,

Fei

**Comment by feipan664** [comment]
Dear author, thank you so much for your effort!
Best regards,

Fei

**Comment by sodi16** [comment]
Thanks a lot for this repo,
I have an issue using the pre-trained model of RobustNet for object detection, I loaded .pth file with torch but it only gave me an Odered dictionnary, and I can't use it as model.eval().
If someone can help me, thanks in advance.

**Comment by shachoi** [comment]
@sodi16 
You can access the model file with "state_dict" key 
Please refer [this link](https://github.com/shachoi/RobustNet/blob/a1feeef8e7816422eeac002de5493e294b0da941/utils/misc.py#L193)

**Comment by sodi16** [comment]
@shachoi 
Thanks a lot for your answer, my question wasn't clear enought sorry, I will write my code
I want to use a pre-trained model of Resnet101 based RobustNet to test on my data, when I load state_dict:
`import torchvision.models as models` <br/> `model = models.resnet101(pretrained=False)`
`model.load_state_dict(torch.load(last_cityscapes_epoch_108_mean-iu_0.79276.pth).get('state_dict'))`
`model.eval()`<br/> 
I got  `RuntimeError: Error(s) in loading state_dict for ResNet:` is it a good way to use this pretrained model?

**Comment by shachoi** [comment]
@sodi16 
You should use our modified ResNet code.
```
from network import Resnet
resnet = Resnet.resnet101(pretrained=True, wt_layer=[0,0,2,2,2,0,0])
for n, m in resnet.layer3.named_modules(): # change to dilated backbone networks
    if 'conv2' in n:
        m.dilation, m.padding, m.stride = (2, 2), (2, 2), (1, 1)
    elif 'downsample.0' in n:
        m.stride = (1, 1)
for n, m in resnet.layer4.named_modules():
    if 'conv2' in n:
        m.dilation, m.padding, m.stride = (4, 4), (4, 4), (1, 1)
    elif 'downsample.0' in n:
        m.stride = (1, 1)
resnet = forgiving_state_restore(resnet, torch.load(last_cityscapes_epoch_108_mean-iu_0.79276.pth).get('state_dict'))
```
Please refer following code.
https://github.com/shachoi/RobustNet/blob/main/optimizer.py#L72
https://github.com/shachoi/RobustNet/blob/main/scripts/train_r101os8_cty_isw.sh#L28
https://github.com/shachoi/RobustNet/blob/main/network/deepv3.py#L319
https://github.com/shachoi/RobustNet/blob/main/network/deepv3.py#L345

**Comment by sodi16** [comment]
@shachoi 
And can you help me for testing it on my own image data, thats the code I used but it doesn't work.
  Thanks for your time.
```
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

with torch.no_grad():
  resnet.eval()
  tensor_img = transform(Image.open('img.jpg'))  output = resnet(tensor_img)
  output = resnet(tensor_img)
  TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not method
```

**Comment by shachoi** [comment]
@sodi16 
Sorry for the delayed response.
It was a bug in our code. I only used the forward() of the DeepV3Plus class.
I fixed the bug in forward() of the ResNet class. Please update your code.
Thank you for reporting the bug!
