### ISSUE TITLE
Question about train split in GTAV dataset.

### ISSUE THREAD

**Issue by zzzqzhou** [shachoi/RobustNet#21]
Dear author,
In your paper, you mentioned that there are 12403 images for a train set in GTAV. However, in your split file 'split_data/gtav_split_train.txt', there are only 12388 image names. Is this a mistake?

**Comment by shachoi** [comment]
Hi,

I remember removing some images that consist only of a single color (e.g., The entire image area is black)
So I conducted the experiments with 12388 images.

Thanks!

**Comment by zzzqzhou** [comment]
Thanks for your relpy.
