### ISSUE TITLE
Implementing ConcatDataset

### ISSUE THREAD

**Issue by suesuekkim** [shachoi/RobustNet#23]
Hello, I am using your code for concatenating several datasets. In your code '__init__.py ' in datasets, I can see that your using ConcatDataset which is implemented in pytorch.utils.data. I'm getting the error as below while concatenating dataset.
![image](https://user-images.githubusercontent.com/78398919/174615489-404bb6cd-d259-4bc2-beaa-eca0f2c5eeff.png)

Do you know why this 'TypeError: object of type 'ABCMeta' has no len()' is occuring? Is it necessary to transform (resize, crop,,,,) the image like in your code  get_train_joint_transform,  get_input_transforms ..etc?
and also what is the difference of ConcatDataset(train_sets) and multi_loader.DomainUniformConcatDataset(args, train_sets)?

And when using ConcatDataset, what happens to the class? Does it all integrate the classes of multiple datasets?

Thank you for reading my issue.

**Comment by sunghac** [comment]
Hi,
Sorry for the delayed response.
Actually, I'm not sure about my answers to your questions.
What is ABCMeta? Is your custom dataset?
Please check if your custom dataset class has "\_\_len\_\_()" function like the following code.
https://github.com/shachoi/RobustNet/blob/1ff5c047d7abaf9ab1a7cca23aff812b2f09de15/datasets/cityscapes.py#L321
Uniform means class uniform sampling in ["Improving semantic segmentation via video propagation and label relaxation"](https://arxiv.org/abs/1812.01593)

Thanks and good luck!
