### ISSUE TITLE
Questions about inference on Mapillary.

### ISSUE THREAD

**Issue by zzzqzhou** [shachoi/RobustNet#24]
Hi,

I have a question about inference on Mapillary dataset. I found that image resolution in Mapillary is not fixed. So, how did you test model on Mapillary dataset? Resizing all images to the same resolution or using slide window? This makes me confused.

**Comment by sunghac** [comment]
Please check the code below
https://github.com/shachoi/RobustNet/blob/1ff5c047d7abaf9ab1a7cca23aff812b2f09de15/datasets/__init__.py#L493
```
eval_size = 1536
val_joint_transform_list = [
    joint_transforms.ResizeHeight(eval_size),
    joint_transforms.CenterCropPad(eval_size)]
```

Thanks!

**Comment by zzzqzhou** [comment]
So you mean you resize and center crop all images into 1536 * 1536 resolution for testing?
