### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by DeepHM** [shachoi/RobustNet#25]
#####
Since I confirmed that the author of the paper was Korean, I wrote the question in Korean.
If I have to write a question in English, if you give me an answer, I will write it.
#####

안녕하세요.
'RobustNet: Improving Domain Generalization in Urban-Scene Segmentation via Instance Selective Whitening'
양질의 논문을 작성해주셔서, 정말 흥미롭게 잘 읽었습니다.
논문 내용과 관련해서 2가지 질문 사항이 있는데,
답변 해주시면 감사하겠습니다.

1. photometric transformation(i.e. color jittering)에 따른 covariance matrix의 elements 확인

원-이미지가 있고 photometric transformation을 통한 변환-이미지 2개가 있을 때,
각각의 covariance matrix of feature map을 계산하고 2개의 covariance matrix의 값을 직접 확인해보고 싶습니다. 
논문에서 언급된 Sensitive covariances는 Illumination이 크게 달라지고, Insensitive covariances는 photometric transformation에 영향을 받지 않고 scene structure에 민감한 부분을 직접 확인해보고 싶은데, 혹시 이에 대한 구현이 있을까요?

2.  feature-covariance matrix 차이에 대한 질문
 
개인적인 생각으로는 일반적인 segmentation model with ResNet backbone은 photometric transformation에 따른 feature-covariance matrix의 elements 차이가 나타나지 않고, model의 layer에 Instance-Normalization 혹은 Loss_DWT와 같은 whitening이 적용된 모델만 photometric transformation에 따른 feature-covariance matrix의 elements가 차이를 나타낼 것으로 보이는데, 혹시 해당 내용이 맞을까요? 아니면, 일반적인 모델도 논문에서 언급된 covariance의 차이를 보일까요?

감사합니다 !
I love LG A.I Research.

**Comment by sunghac** [comment]
안녕하세요. 아래와 같이 답변 드립니다.
1. 죄송하지만 해당 코드는 별도로 정리를 하지 않아서 현재는 찾기가 어렵네요. 다만 이에 대한 구현은 어렵지 않은데, 학습되어진 baseline 모델을 이용하여, 원본이미지 들과 그것들의 transformed 이미지들을 forward 하여 구한 두 개의 covariance matrix 들로부터 "covariance matrix 의 분산 matrix" 를 구합니다. 그 후에 그 matrix 의 off-diagonal elements 중에서 값이 가장 큰 지점 (i.e., 분산이 큰 지점)을 i, 그리고 값이 작은 지점을 찾아서 j 라고 합니다. 그 후에 이미지들을 forward 하면서 covariance matrix 를 구하고 covariance matrix 의 i 지점 그리고 j 지점의 값을 기준으로 이미지들을 정렬 하면 이미지 들의 특성을 살펴볼 수 있습니다. 즉 이는 해당 지점의 covariance 들이 어떠한 정보를 가지고 있는지 대략적이지만 살펴볼 수 있는 방법이 될 수 있습니다.
2. 제 생각에는 반대일 거 같은데요. baseline 모델은 더욱 photometric transformation 에 따른 covariance 의 분산이 클 것이라고 생각이 들고 (어떤 제약도 가하지 않았기 때문에), ISW 가 적용된 것은 photometric transform 에 따른 분산이 큰 covariance 를 제약하기 때문에 분산이 작아질 것 같습니다.

답변이 되었으면 좋겠네요. 감사합니다.

**Comment by DeepHM** [comment]
> 
논문 재확인하고 코드 분석하며 re-implementation 해보느라 늦었습니다.
친절한 답변 덕분에 아래 사진처럼, 재구현하여 확인할 수 있었습니다!
연구에 많은 도움이 될 것 같네요. 감사드립니다 :)


![robustnet_figure2reimple](https://user-images.githubusercontent.com/37736774/180152265-ab84c543-6560-47d6-b29d-e7346d16b3f2.JPG)


다시 한번 감사 드립니다!

**Comment by sunghac** [comment]
와 실제로 재구현 하시고 결과도 의도한 대로 나와서 다행이네요! 이렇게 관심 가져주셔서 저도 정말 감사드립니다. 좋은연구 하셔서 좋은결과 있으시면 좋겠네요 감사합니다~
