### ISSUE TITLE
Uniform dataset

### ISSUE THREAD

**Issue by azshue** [shachoi/RobustNet#3]
Hi,

I came across this Uniform dataset in your implementation. For example the class [GTAVUniform](https://github.com/shachoi/RobustNet/blob/0538c69954c030273b3df952f90347572ecac53b/datasets/gtav.py#L306) in `datasets/gtav.py`. 
This uniform dataset appears to be the default dataset for your baselines, but I haven't found any info about it in the Readme or the paper. Could you help me understand what is it for?

Thanks!

**Comment by shachoi** [comment]
Hi,
We followed the implementation detail of [NVIDIA segmentation](https://github.com/NVIDIA/semantic-segmentation) and [HANet](https://github.com/shachoi/HANet). GTAVUniform means the dataset to which Class Uniform Sampling proposed in [This paper](https://openaccess.thecvf.com/content_CVPR_2019/papers/Zhu_Improving_Semantic_Segmentation_via_Video_Propagation_and_Label_Relaxation_CVPR_2019_paper.pdf) is applied.
Class uniform sampling was applied to all experiments on GTAV or Cityscape.

Thank you!

**Comment by shachoi** [comment]
@azshue 
Thanks for the good point. I missed the explanation of class uniform sampling in our paper and README file.

**Comment by azshue** [comment]
Thank you for your prompt reply! 
My question is answered, and I'll close the issue.
