### ISSUE TITLE
Question about the results and a bug

### ISSUE THREAD

**Issue by Making24** [shachoi/RobustNet#4]
Hi, Thanks for your great work!

I have run the code for MobileNet, however, I get largely lower results than your reported results.

I got the following results:

MobileNet-Base, mIoU = 20.12%

MobileNet-IBN, mIoU = 27.41%

MobileNet-ISW, mIoU = 23.24%

All results are tested on the last model and on the CityScapes.

I also found an error when loading the dataset,

https://github.com/shachoi/RobustNet/blob/55e385a6600482793cf64544217678196dbcd3b8/datasets/gtav.py#L438

This line will causes ``TypeError: 'bool' object is not subscriptable'' for Pthon 3.

And I change:

`mask_copy[(mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2]] = v
`

**to**

```
sel_mask = np.logical_and(mask[:, :, 0] == np.array(k)[0], mask[:, :, 1] == np.array(k)[1], mask[:, :, 2] == np.array(k)[2])
mask_copy[sel_mask] = v
```

for all the dataset loaders.

I am not sure if this causes the low results. Could you help me to address this problem? Thanks!

**Comment by shachoi** [comment]
Hi,
Sorry for the delayed response.

Did you validate our pre-trained MobileNet?
I added a function to verify the performance of the pre-trained model.
Please refer [this link](https://github.com/shachoi/RobustNet#pretrained-models).

Thank you for your interest in our work!

**Comment by Making24** [comment]
@shachoi Hi, Thanks for your reply!

Yes, the pre-trained model can produce the reported results.

However, I train your models with your source code. But I get the above results. The only modified codes are the 
`mask_copy[(mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2]] = v`

I checked the results of the final iteration. But the results are largely lower than your pre-trained models.

**Comment by shachoi** [comment]
@Making24 
To clarify, did you use [the script file](https://github.com/shachoi/RobustNet/blob/main/scripts/train_mobile_gtav_isw.sh) I uploaded without modification? (e.g. batch size, number of GPUs, etc.)
The above error does not occur in my environment, so the error seems to occur depending on the Python version.

Thanks!

**Comment by Making24** [comment]
@shachoi No, I did not change the scripts.

Yes, for python3, I change the code to 
`sel_mask = np.logical_and(mask[:, :, 0] == np.array(k)[0], mask[:, :, 1] == np.array(k)[1], mask[:, :, 2] == np.array(k)[2])
mask_copy[sel_mask] = v`

And I think this code is the same to
` mask_copy[(mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2]] = v 
`

**Comment by shachoi** [comment]
Hi,

I checked your code, but there are some errors in using np.logical_and().
I tested your code as follows.
```
for k, v in color_to_trainid.items():
    if v != 255 and v != -1:
        mask_copy[(mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2]] = v
        sel_mask = np.logical_and(mask[:, :, 0] == np.array(k)[0], mask[:, :, 1] == np.array(k)[1], mask[:, :, 2] == np.array(k)[2])
        mask_copy[sel_mask] = v
        print("1", np.array_equal((mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2], sel_mask))
        sel_mask = np.logical_and((mask == np.array(k))[:,:,0],  (mask == np.array(k))[:,:,1])
        sel_mask = np.logical_and(sel_mask, (mask == np.array(k))[:,:,2])
        print("2", np.array_equal((mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2], sel_mask))
```
However, the output was as follows:
...
1 False
1 False
2 True
2 True

Please check the usage of np.logical_and().

Thank you!

**Comment by Making24** [comment]
@shachoi 

Thanks for your feedback. I am sorry for the mistake. I will use your proposed code instead and check the results again. I will let you know the results.

On the other hand, 
`        mask_copy[(mask == np.array(k))[:,:,0] & (mask == np.array(k))[:,:,1] & (mask == np.array(k))[:,:,2]] = v
`
will cause an error for python. 

Therefore, could you also update the code so that it can also fit to both python 2 and 3? I think many guys are using python 3 too.

Thanks

**Comment by Making24** [comment]
@shachoi 

Hi, `mask == np.array(k))[:,:,0]` can not be used in python 3. It will report `TypeError: 'bool' object is not subscriptable`.

How to address it in Python 3?

**Comment by shachoi** [comment]
Can you check the following requirements?
```
conda create --name robustnet python=3.7
conda activate robustnet
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
conda install scipy==1.1.0
conda install tqdm==4.46.0
conda install scikit-image==0.16.2
pip install tensorboardX
pip install thop
pip install kmeans1d
imageio_download_bin freeimage
```

**Comment by Making24** [comment]
@shachoi My server has scipy==1.4.1 and there is no 'imread' function for it. However, I can not change the version in my server and I use imageio instead. When using imageio,  the size of the mask is (H, W, 4). Is it the same as the one generated by script?

**Comment by shachoi** [comment]
The result is the same in our environment.
Thank you!
```
07-21 02:21:43.852 Class Uniform Percentage: 0.5
07-21 02:21:43.854 Class Uniform items per Epoch:12388
07-21 02:21:43.857 cls 0 len 12109
07-21 02:21:43.857 cls 1 len 11833
07-21 02:21:43.857 cls 2 len 12301
07-21 02:21:43.857 cls 3 len 10854
07-21 02:21:43.857 cls 4 len 8811
07-21 02:21:43.857 cls 5 len 11928
07-21 02:21:43.857 cls 6 len 7891
07-21 02:21:43.857 cls 7 len 5921
07-21 02:21:43.857 cls 8 len 12132
07-21 02:21:43.857 cls 9 len 11549
07-21 02:21:43.857 cls 10 len 12131
07-21 02:21:43.858 cls 11 len 10691
07-21 02:21:43.858 cls 12 len 986
07-21 02:21:43.858 cls 13 len 10501
07-21 02:21:43.858 cls 14 len 6711
07-21 02:21:43.858 cls 15 len 1861
07-21 02:21:43.858 cls 16 len 493
07-21 02:21:43.858 cls 17 len 1211
07-21 02:21:43.858 cls 18 len 168
07-21 02:21:43.864 val fine cities: ['valid/1']
07-21 02:21:43.910 GTAV-val: 6382 images
07-21 02:21:43.911 val fine cities:
07-21 02:21:43.915 BDD100K-val: 1000 images
07-21 02:21:43.915 val fine cities: ['val/lindau', 'val/munster', 'val/frankfurt']
07-21 02:21:43.918 Cityscapes-val: 500 images
07-21 02:21:43.918 val fine cities:
07-21 02:21:43.928 Synthia-val: 2820 images
```

**Comment by Making24** [comment]
@shachoi Thanks! I have revised the code. I think it is the same with you now. I will rerun the code and let you know the results.

**Comment by Making24** [comment]
@shachoi 

I test the models of the last iteration.

Mobile_IBN=26.7% (lower than reported results (30.14))

Moible_ISW=30.03% (lower than reported results (30.86))

I also found that IBN can achieve higher results in small epochs.

epoch=1, Mobile_IBN=28.62%
epoch=16, Mobile_IBN=30.27%
epoch=24, Mobile_IBN=28.66%
epoch=45, Mobile_IBN=28.32%

**Comment by shachoi** [comment]
As I described in our paper, we reported performance on the last iteration for all experiments.
The results of all experiments were performed three times and are the average of the values.

**Comment by Making24** [comment]
Ok. But currently, I can not well reproduce the results in the paper.

Mobile_IBN is largely lower and Mobile_ISW is 0.8% lower than the reported results.

Waiting for others for reproducing.
