### ISSUE TITLE
Running RobustNet with ResNet-101 backbone and DeepLab v2 decoder

### ISSUE THREAD

**Issue by fabriziojpiva** [shachoi/RobustNet#6]
Hi,

Thanks for such a nice work! I was wondering if it is possible to reproduce somehow the results of Fig. 9, where you compare with DA methods. Did you change the backbone to ResNet-101 + DeepLab v2 to compare with those UDA methods (Appendix A.1)? Or did you _downscale_ their backbone to Resnet-50 and changed their decoder to DeepLab v3+?

If you changed your backbone to ResNet-101 + DeepLab v2, is it possible to run an experiment with this setting? What steps should I take?

**Comment by shachoi** [comment]
We did not make the segmentation architecture and backbone of all methods identical in the experiments in Figure 9.  (There are actually too many variations)
Figure 9 can be understood as a **"relative comparison"** of the performance gains over baseline for each method.

Thanks!

**Comment by fabriziojpiva** [comment]
Thanks for the reply, so if I understand correctly, the results of Fig. 9 are also using ResNet-50?

Another question, I saw in the scripts folder that you have a script to train with Resnet-101 backbone: files `train_r101os8_cty_base.sh` and `train_r101os8_cty_isw.sh`. I would like to train your model with ResNet-101 and DeepLab v2, is it possible to use those scripts along with adding the decoder for DeepLab v2 in the network folder?

**Comment by shachoi** [comment]
Right. We use ResNet-50 for the experiments in Fig.9.

Yes, you just need to use the same script files and change the decoder part of [network/deepv3.py](https://github.com/shachoi/RobustNet/blob/main/network/deepv3.py) file.
ISW loss only affects the encoder part.

Thank you!

**Comment by Making24** [comment]
@fabriziojpiva I implemented ISW with ResNet-101. However, I got low results that are similar to ResNet-50. Did you produce reasonable results for ResNet-101?

**Comment by shachoi** [comment]
duplicate

**Comment by shachoi** [comment]
duplicated with https://github.com/shachoi/RobustNet/issues/9
