### ISSUE TITLE
Error during training when performing evaluation

### ISSUE THREAD

**Issue by fabriziojpiva** [shachoi/RobustNet#7]
Hi, I would like to let you know that there is a small bug when training. I tried to run the script `train_r50os16_cty_isw.sh` to reproduce the results of your paper when you train with Cityscapes using output stride of 16.

Specifically, the error happens when performing evaluation in this line:

https://github.com/shachoi/RobustNet/blob/6e172bddc010eb27739f1930125bf5170207bed9/train.py#L259

because you are passing `None` and `None` to the parameters `val_loss` and `hist`, and you have repetitive if statements inside that function asking whether those variables are not `None`:

https://github.com/shachoi/RobustNet/blob/6e172bddc010eb27739f1930125bf5170207bed9/utils/misc.py#L144

And at the end of that function, you have the following line(s) to store in the writer the accuracy, mean iou, etc.:

https://github.com/shachoi/RobustNet/blob/6e172bddc010eb27739f1930125bf5170207bed9/utils/misc.py#L251

but those variables `acc`, `acc_cls`, `val_loss` are not declared, because the execution never entered in any of those if's statements where you calculate these variables. So the training script throws an error saying:

`Traceback (most recent call last):
  File "train.py", line 544, in <module>
    main()
  File "train.py", line 260, in main
    writer, epoch, "None", None, i, save_pth=True)
  File "/home/fabrizio/Projects/umdg/dg/RobustNet/utils/misc.py", line 263, in evaluate_eval
    acc_cls, curr_iter)
UnboundLocalError: local variable 'acc' referenced before assignment`

**Comment by shachoi** [comment]
Hi @fabriziojpiva,
Thanks for the bug report and kind explanation!
Fixed [this version](https://github.com/shachoi/RobustNet/commit/56cb41baa286082dfa7f534ea56750bc091e1842).

The code below is simply for saving the model.
https://github.com/shachoi/RobustNet/blob/6e172bddc010eb27739f1930125bf5170207bed9/train.py#L259
The performance measurement is done in the code below.
https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/train.py#L476

Thank you!
