### ISSUE TITLE
Question about the variance matrix

### ISSUE THREAD

**Issue by userb2020** [shachoi/RobustNet#8]
Hello.
Thank you for sharing your great code!

I have a question about the variance matrix **V**.

When I first read the paper, I thought that **V** was calculated per image pair.
However, in the code, it turns out that **V** was calculated per layer.
Also, **V** was not calculated during the training stage, but in the validation stage.

Is there a reason why you design the calculation of **V** like in the code?

Thank you.

**Comment by shachoi** [comment]
Hi, Thank you for your interest in our paper and code!

As stated in the paper, it is correct to calculate the variance of the covariance between the photometric transformed image and the original image. Those two images are concatenated as a batch dimension (dim=0) and the variance is obtained via torch.var().
https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/train.py#L505
https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/network/deepv3.py#L480-L481
https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/network/deepv3.py#L543

The following codes with "validate_for_cov_stat" for calculating the variance matrix are included in the training phase. 
![image](https://user-images.githubusercontent.com/34509882/128633577-d928e8b0-fce2-4350-a9de-f3fa4d2b5da0.png)

https://github.com/shachoi/RobustNet/blob/56cb41baa286082dfa7f534ea56750bc091e1842/train.py#L239-L269

If you have further questions, please feel free to ask.
Thank you!
